name: Terraform WBD sandbox (Terragrunt)

on:
  workflow_dispatch:
    inputs:
      intake_id:
        description: "users/<INTAKE_ID> (e.g., intake_001)"
        required: true
        default: "intake_001"

jobs:
  tf:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID:     ${{ fromJSON(secrets.WBD_SANDBOX_SECRET).AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ fromJSON(secrets.WBD_SANDBOX_SECRET).AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION:    us-east-1
      INTAKE_DIR:            live/sandbox/users/${{ github.event.inputs.intake_id }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show caller identity (should be DESTINATION account)
        run: aws sts get-caller-identity

      - name: Install Terraform
        run: |
          curl -sSLo terraform.zip https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
          sudo unzip -o terraform.zip -d /usr/local/bin
          terraform -version

      - name: Install Terragrunt
        run: |
          TG_VERSION=0.66.9
          curl -sSL -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v${TG_VERSION}/terragrunt_linux_amd64
          sudo install -m 0755 terragrunt /usr/local/bin/terragrunt
          terragrunt --version

      - name: Plan & Apply (IAM → S3 → VPC → KeyPair → EC2)
        shell: bash
        run: |
          set -euo pipefail

          apply_if_exists () {
            local dir="$1"
            if [[ -d "$dir" ]]; then
              echo "::group::Applying $dir"
              cd "$dir"
              terragrunt init -upgrade --terragrunt-non-interactive
              terragrunt validate --terragrunt-non-interactive
              terragrunt plan -out=tfplan.bin --terragrunt-non-interactive
              terragrunt apply -auto-approve tfplan.bin --terragrunt-non-interactive
              cd - >/dev/null
              echo "::endgroup::"
            else
              echo "SKIP: $dir (not present)"
            fi
          }

          # Ensure parent marker exists for find_in_parent_folders() lookups
          if [[ ! -f "$INTAKE_DIR/terragrunt.hcl" ]]; then
            echo "locals {}" > "$INTAKE_DIR/terragrunt.hcl"
          fi

          apply_if_exists "$INTAKE_DIR/iam"
          apply_if_exists "$INTAKE_DIR/s3"
          apply_if_exists "$INTAKE_DIR/vpc"
          apply_if_exists "$INTAKE_DIR/keypair"
          apply_if_exists "$INTAKE_DIR/ec2"
